#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${PRODUCTION_ENV_FILE:-}"
EVIDENCE_DIR="${RELEASE_EVIDENCE_DIR:-$ROOT/release-evidence}"
OUT_DIR="${PREFLIGHT_ARTIFACT_DIR:-$ROOT/../healthpoint/artifacts/preflight-production}"
RENDERED_MANIFEST_DIR="${RENDERED_MANIFEST_DIR:-$OUT_DIR/rendered-manifests}"
mkdir -p "$OUT_DIR"
fail() { echo "PREFLIGHT_FAIL: $*" >&2; exit 2; }
[[ -n "$ENV_FILE" && -f "$ENV_FILE" ]] || fail "PRODUCTION_ENV_FILE must reference a protected environment file"
set -a; source "$ENV_FILE"; set +a
node "$ROOT/scripts/validate-production-env.mjs" >"$OUT_DIR/environment-validation.json" || fail "production environment validation failed"
node "$ROOT/scripts/validate-postgresql-migration-journal.mjs" >"$OUT_DIR/migration-journal-validation.json" || fail "PostgreSQL migration journal validation failed"
pnpm --dir "$ROOT" run check:platform-independence >"$OUT_DIR/platform-independence.json" 2>&1 || fail "platform-independence validation failed"
pnpm --dir "$ROOT" run check:cms-manual-handoff >"$OUT_DIR/cms-manual-handoff-policy.json" 2>&1 || fail "CMS manual-handoff policy validation failed"
pnpm --dir "$ROOT" run check:telemetry-coverage >"$OUT_DIR/telemetry-coverage.json" 2>&1 || fail "telemetry coverage validation failed"
pnpm --dir "$ROOT" run validate:production-manifests >"$OUT_DIR/source-manifest-validation.json" 2>&1 || fail "production source manifest validation failed"
pnpm --dir "$ROOT" run check:external-gate-templates >"$OUT_DIR/external-gate-template-policy.json" 2>&1 || fail "external-gate staging template policy validation failed"
pnpm --dir "$ROOT" run validate:tigerbeetle-drill-alert-routing >"$OUT_DIR/tigerbeetle-drill-alert-routing.json" 2>&1 || fail "TigerBeetle drill alert routing validation failed"
pnpm --dir "$ROOT" run validate:tigerbeetle-drill-workflow >"$OUT_DIR/tigerbeetle-drill-workflow.json" 2>&1 || fail "TigerBeetle drill workflow validation failed"
pnpm --dir "$ROOT" run validate:tigerbeetle-cni-query-fixtures >"$OUT_DIR/tigerbeetle-cni-query-fixtures.log" 2>&1 || fail "TigerBeetle CNI query fixture validation failed"
pnpm --dir "$ROOT" run validate:tigerbeetle-drill-log-access-contract >"$OUT_DIR/tigerbeetle-drill-log-access-contract.log" 2>&1 || fail "TigerBeetle drill log access contract validation failed"
pnpm --dir "$ROOT" run validate:tigerbeetle-gitops-deployment-contract >"$OUT_DIR/tigerbeetle-gitops-deployment-contract.log" 2>&1 || fail "TigerBeetle GitOps deployment contract validation failed"
pnpm --dir "$ROOT" run test:tigerbeetle-gitops-deployment-contract >"$OUT_DIR/tigerbeetle-gitops-deployment-contract-test.log" 2>&1 || fail "TigerBeetle GitOps negative fixture test failed"
pnpm --dir "$ROOT" run validate:tigerbeetle-clock-synchronization-contract >"$OUT_DIR/tigerbeetle-clock-synchronization-contract.log" 2>&1 || fail "TigerBeetle clock synchronization contract validation failed"
pnpm --dir "$ROOT" run test:tigerbeetle-clock-monitor-guards >"$OUT_DIR/tigerbeetle-clock-monitor-guards.log" 2>&1 || fail "TigerBeetle clock monitor guard suite failed"
pnpm --dir "$ROOT" run test:tigerbeetle-clock-monitor-integration >"$OUT_DIR/tigerbeetle-clock-monitor-integration.log" 2>&1 || fail "TigerBeetle clock monitor mTLS fixture integration suite failed"
pnpm --dir "$ROOT" run test:tigerbeetle-lifecycle-metrics >"$OUT_DIR/tigerbeetle-lifecycle-metrics.log" 2>&1 || fail "TigerBeetle lifecycle metrics suite failed"
pnpm --dir "$ROOT" run test:tigerbeetle-finality >"$OUT_DIR/tigerbeetle-finality.log" 2>&1 || fail "TigerBeetle durable finality fail-closed suite failed"
pnpm --dir "$ROOT" run test:stakeholder-attestation-crypto >"$OUT_DIR/stakeholder-attestation-crypto.log" 2>&1 || fail "Stakeholder cryptographic attestation suite failed"
pnpm --dir "$ROOT" run test:tigerbeetle-finality-evidence-import >"$OUT_DIR/tigerbeetle-finality-evidence-import.log" 2>&1 || fail "TigerBeetle finality evidence-import guard suite failed"
pnpm --dir "$ROOT" run validate:tigerbeetle-staging-topology >"$OUT_DIR/tigerbeetle-staging-topology.log" 2>&1 || fail "TigerBeetle six-replica topology contract validation failed"
pnpm --dir "$ROOT" run validate:tigerbeetle-clock-monitor-deployment-contract >"$OUT_DIR/tigerbeetle-clock-monitor-deployment-contract.log" 2>&1 || fail "TigerBeetle clock monitor deployment contract validation failed"
pnpm --dir "$ROOT" run validate:tigerbeetle-clock-metrics-terraform-contract >"$OUT_DIR/tigerbeetle-clock-metrics-terraform-contract.log" 2>&1 || fail "TigerBeetle clock metrics Terraform contract validation failed"
pnpm --dir "$ROOT" run validate:tigerbeetle-clock-dashboard >"$OUT_DIR/tigerbeetle-clock-dashboard.log" 2>&1 || fail "TigerBeetle clock dashboard validation failed"
pnpm --dir "$ROOT" run test:tigerbeetle-alertmanager-routing:dry-run >"$OUT_DIR/tigerbeetle-local-alertmanager-dry-run.log" 2>&1 || fail "TigerBeetle local Alertmanager routing dry-run failed"
pnpm --dir "$ROOT" run test:tigerbeetle-local-alertmanager-routing-analysis >"$OUT_DIR/tigerbeetle-local-alertmanager-routing-analysis.log" 2>&1 || fail "TigerBeetle local Alertmanager routing-log analysis test failed"
pnpm --dir "$ROOT" run test:tigerbeetle-staging-alertmanager-routing-drill-guards >"$OUT_DIR/tigerbeetle-staging-alertmanager-routing-drill-guards.log" 2>&1 || fail "TigerBeetle staging Alertmanager routing drill guard suite failed"
pnpm --dir "$ROOT" run test:tigerbeetle-staging-alertmanager-routing-evidence >"$OUT_DIR/tigerbeetle-staging-alertmanager-routing-evidence.log" 2>&1 || fail "TigerBeetle staging Alertmanager routing evidence fixture suite failed"
node "$ROOT/scripts/validate-production-compose-env.mjs" >"$OUT_DIR/production-compose-environment.json" || fail "production Compose environment validation failed"
RENDERED_MANIFEST_DIR="$RENDERED_MANIFEST_DIR" node "$ROOT/scripts/render-production-manifests.mjs" >"$OUT_DIR/manifest-render.json" 2>&1 || fail "immutable manifest rendering failed"
RENDERED_MANIFEST_DIR="$RENDERED_MANIFEST_DIR" node "$ROOT/scripts/validate-production-manifests.mjs" --rendered >"$OUT_DIR/rendered-manifest-validation.json" 2>&1 || fail "rendered production manifest validation failed"
node "$ROOT/scripts/assurance-gate.mjs" --release >"$OUT_DIR/assurance-gate.log" 2>&1 || fail "assurance/release gate failed"
EVIDENCE_EXECUTION=protected RELEASE_EVIDENCE_DIR="$EVIDENCE_DIR" \
  node "$ROOT/scripts/validate-external-release-blockers.mjs" --evidence-dir "$EVIDENCE_DIR" >"$OUT_DIR/external-blockers.json" 2>&1 || fail "external release evidence is incomplete"
pnpm run check >"$OUT_DIR/typecheck.log" 2>&1 || fail "TypeScript check failed"
pnpm run build >"$OUT_DIR/build.log" 2>&1 || fail "production build failed"
git -C "$ROOT" diff --check >"$OUT_DIR/diff-check.log" 2>&1 || fail "whitespace/diff check failed"
printf '%s\n' 'PREFLIGHT_PASS: all production deployment gates passed'
