---
apiVersion: v1
kind: Namespace
metadata:
  name: healthpoint
  labels:
    name: healthpoint
    app.kubernetes.io/part-of: healthpoint-platform
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: healthpoint-middleware
  labels:
    name: healthpoint-middleware
    app.kubernetes.io/part-of: healthpoint-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: healthpoint-monitoring
  labels:
    name: healthpoint-monitoring
    app.kubernetes.io/part-of: healthpoint-platform
