/**
 * server/temporal/lakehouse.shared.ts
 *
 * PURE types/constants shared by the lakehouse-export workflow, activities,
 * worker, and schedule helper. Workflow bundles may only import
 * side-effect-free modules — this file must NEVER import server/db, routers,
 * or Node I/O (same rule as journeys.shared.ts).
 */

/** Datasets exported incrementally (mirrors server/lakehouse/export.ts). */
export const LAKEHOUSE_EXPORT_DATASETS = ["disputes", "documents", "audit"] as const;
export type LakehouseExportDataset = (typeof LAKEHOUSE_EXPORT_DATASETS)[number];

export interface LakehouseExportWorkflowInput {
  /** Datasets to export; defaults to LAKEHOUSE_EXPORT_DATASETS. */
  datasets?: LakehouseExportDataset[];
  /** Correlates bookkeeping run rows; generated by the schedule when absent. */
  runId?: string;
}

export interface LakehouseDatasetExportResult {
  dataset: LakehouseExportDataset;
  rowCount: number;
  s3Key: string | null;
  previousWatermark: string | null;
  newWatermark: string | null;
}

export interface LakehouseExportSummary {
  runId: string;
  datasets: LakehouseExportDataset[];
  results: LakehouseDatasetExportResult[];
  totalRows: number;
  failures: string[];
  succeeded: boolean;
}
